eureka:
  instance:
    hostname: http://ec2-18-237-57-72.us-west-2.compute.amazonaws.com

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ec2-18-237-57-72.us-west-2.compute.amazonaws.com:${server.port}/eureka/
