eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://innofi-service-registry.herokuapp.com/eureka/

    instance:
      hostname: https://innofi-service-registry.herokuapp.com
