eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://innofi-service-registry.herokuapp.com:8761/eureka/

    instance:
      hostname: localhost
