eureka:
  instance:
    prefer-ip-address: true
    hostname: http://18.237.57.72:8761/
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://18.237.57.72:8761/eureka/
