eureka:
  instance:
    hostname: innofi-service-registry.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://${innofi-service-registry.herokuapp.com:http://localhost:8761/eureka}
