eureka:
  instance:
    hostname: ec2-18-237-57-72.us-west-2.compute.amazonaws.com

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ec2-18-237-57-72.us-west-2.compute.amazonaws.com:8761/eureka/
