eureka:
  instance:
    #hostname: innofi-service-registry.herokuapp.com
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
